"""AST-aware-ish chunking for decompiled ``.java`` / ``.kt`` sources.

We do *not* depend on tree-sitter here. jadx output already has predictable
shape (one top-level class per file, generated by a consistent decompiler),
and we only need accuracy good enough that:

* method boundaries land on real braces (so a chunk is a complete method),
* class headers (``class Foo extends Bar implements Baz``) survive intact,
* anonymous inner classes and lambdas are not chunked separately (they ride
  with the enclosing method).

The chunker emits two kinds of chunks per file:

* ``class_header`` — package + imports + class declaration line + javadoc,
  capped at ``CLASS_HEADER_MAX_CHARS``. Gives the embedder type context.
* ``method`` — one signature-to-matching-brace block per method, optionally
  re-windowed when the body exceeds ``METHOD_TARGET_CHARS``.

Brace-balancing is comment- and string-aware (``//``, ``/* */``, ``"…"``,
``'…'``, triple-quoted Kotlin strings) but does *not* try to parse Kotlin
string interpolation perfectly — close enough for chunk boundaries.

Why character budgets, not token counts? Token counts depend on the chosen
embedding model's tokenizer; loading those tokenizers just to slice text
is overkill. The chars/4 ≈ tokens heuristic works for every embedding
provider we ship.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Iterator, Optional

# A single chunk that we will embed and store. ``content`` is the text fed
# to the embedder; ``preview`` is a short snippet shown in the UI.
@dataclass(frozen=True)
class Chunk:
    file: str  # path relative to sources_root
    package: str
    class_name: str
    method_name: Optional[str]  # None for class_header chunks
    kind: str  # "class_header" | "method"
    start_line: int  # 1-based, inclusive
    end_line: int  # 1-based, inclusive
    content: str  # text fed to the embedder

    def chunk_id(self) -> str:
        """Stable id used as the SQLite primary key."""
        m = self.method_name or "_header"
        return f"{self.file}#{self.kind}:{self.class_name}.{m}@L{self.start_line}-{self.end_line}"

    def preview(self, max_chars: int = 240) -> str:
        body = self.content.strip()
        return body if len(body) <= max_chars else body[: max_chars - 1] + "…"


# Tunables. These are conservative: a typical method on weakbank fits in one
# chunk; large generated builders (R.java, Dagger glue) get windowed.
METHOD_TARGET_CHARS = 1600  # ~400 tokens
METHOD_OVERLAP_CHARS = 200
CLASS_HEADER_MAX_CHARS = 1200
MAX_FILE_BYTES = 512_000  # skip absurdly large files (obfuscated mega-classes)
MAX_METHOD_CHARS = 16_000  # if a method is bigger than this, window aggressively


_CLASS_RE = re.compile(
    r"(?m)^[ \t]*(?:public|private|protected|static|final|abstract|sealed|open|"
    r"data|inner|companion|object|@?\w+\s+)*"
    r"(?:class|interface|enum|@interface|object)\s+([A-Za-z_][A-Za-z0-9_$]*)"
)
_PACKAGE_RE = re.compile(r"(?m)^\s*package\s+([\w.]+)\s*;?\s*$")
_METHOD_BLACKLIST = {
    "if", "for", "while", "switch", "synchronized", "catch", "try",
    "return", "do", "else", "new", "throw", "yield", "when",
}

# Method signature heuristic: matches a signature line ending in ``)`` followed
# by an optional ``throws ...`` clause, terminated by ``{``. Captures the name.
# Multi-line signatures are handled by feeding ``re.MULTILINE`` and allowing
# whitespace including newlines inside the parameter list.
_METHOD_RE = re.compile(
    r"(?m)^(?P<indent>[ \t]*)"
    r"(?:(?:public|private|protected|static|final|synchronized|native|abstract|"
    r"default|override|open|inline|operator|suspend|tailrec|infix)\s+)*"
    r"(?:(?:fun)\s+|"  # Kotlin
    r"(?:[A-Za-z_][\w<>\[\],?\s.&]*?)\s+)?"  # Java return type
    r"(?P<name>[A-Za-z_][A-Za-z0-9_$]*)\s*"
    r"\([^;{)]*\)\s*"
    r"(?::\s*[A-Za-z_][\w<>\[\],?\s.]*\s*)?"  # Kotlin return-type ": Foo"
    r"(?:throws\s+[^{;]+)?\s*\{"
)


def _strip_comments_for_balance(s: str) -> str:
    """Replace comments and strings with same-length spaces (preserves indices).

    We need original indices so that line numbers and slice offsets line up
    with the raw source. Returning a same-length sentinel string is the
    simplest way.
    """
    out = list(s)
    i = 0
    n = len(s)
    while i < n:
        c = s[i]
        nxt = s[i + 1] if i + 1 < n else ""
        # // line comment
        if c == "/" and nxt == "/":
            j = s.find("\n", i)
            j = n if j == -1 else j
            for k in range(i, j):
                if out[k] != "\n":
                    out[k] = " "
            i = j
            continue
        # /* block comment */
        if c == "/" and nxt == "*":
            j = s.find("*/", i + 2)
            j = n if j == -1 else j + 2
            for k in range(i, j):
                if out[k] != "\n":
                    out[k] = " "
            i = j
            continue
        # Triple-quoted string (Kotlin)
        if c == '"' and s[i:i + 3] == '"""':
            j = s.find('"""', i + 3)
            j = n if j == -1 else j + 3
            for k in range(i, j):
                if out[k] != "\n":
                    out[k] = " "
            i = j
            continue
        # Regular string
        if c == '"':
            j = i + 1
            while j < n:
                if s[j] == "\\":
                    j += 2
                    continue
                if s[j] == '"':
                    j += 1
                    break
                if s[j] == "\n":
                    break  # unterminated -> bail (jadx sometimes emits this)
                j += 1
            for k in range(i, j):
                if out[k] != "\n":
                    out[k] = " "
            i = j
            continue
        # Char literal
        if c == "'":
            j = i + 1
            while j < n:
                if s[j] == "\\":
                    j += 2
                    continue
                if s[j] == "'":
                    j += 1
                    break
                if s[j] == "\n":
                    break
                j += 1
            for k in range(i, j):
                if out[k] != "\n":
                    out[k] = " "
            i = j
            continue
        i += 1
    return "".join(out)


def _matching_brace(masked: str, open_idx: int) -> int:
    """Index of the ``}`` that matches the ``{`` at ``open_idx`` in ``masked``.

    Returns ``len(masked)`` if unbalanced (treat as 'rest of file' so we never
    silently produce a phantom chunk that excludes part of a method).
    """
    depth = 0
    for k in range(open_idx, len(masked)):
        c = masked[k]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return k
    return len(masked)


def _line_of(source: str, idx: int) -> int:
    """1-based line number of ``idx`` in ``source``."""
    return source.count("\n", 0, idx) + 1


def _window(text: str, target: int, overlap: int) -> Iterator[tuple[int, int, str]]:
    """Yield ``(rel_start, rel_end, slice)`` windows over ``text``.

    Windows align on newlines so chunk boundaries don't split mid-statement.
    """
    n = len(text)
    if n <= target:
        yield 0, n, text
        return
    pos = 0
    while pos < n:
        end = min(n, pos + target)
        # Snap end to the next newline if we're close to one (within overlap).
        nl = text.rfind("\n", pos + target - overlap, end)
        if nl > pos:
            end = nl
        yield pos, end, text[pos:end]
        if end >= n:
            break
        pos = max(pos + 1, end - overlap)


def _read_file(path: Path) -> Optional[str]:
    """Read ``path`` skipping it if it's larger than ``MAX_FILE_BYTES``."""
    try:
        size = path.stat().st_size
    except OSError:
        return None
    if size > MAX_FILE_BYTES:
        return None
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def _package_of(source: str) -> str:
    m = _PACKAGE_RE.search(source)
    return m.group(1) if m else "(default)"


def _primary_class(source: str) -> str:
    m = _CLASS_RE.search(source)
    return m.group(1) if m else "Unknown"


def _class_header_text(source: str, max_chars: int) -> str:
    """Return package + imports + first ``class`` declaration line."""
    m = _CLASS_RE.search(source)
    if not m:
        head = source[:max_chars]
        return head
    decl_end = source.find("\n", m.end())
    decl_end = len(source) if decl_end == -1 else decl_end
    head = source[:decl_end]
    if len(head) > max_chars:
        # Always preserve the class declaration line itself.
        decl_start = source.rfind("\n", 0, m.start()) + 1
        decl = source[decl_start:decl_end]
        prefix_budget = max_chars - len(decl) - 4
        if prefix_budget < 0:
            return decl[:max_chars]
        return source[:prefix_budget] + "\n…\n" + decl
    return head


def chunk_file(rel_path: str, source: str) -> list[Chunk]:
    """Chunk a single source file. Returns ``[]`` for files we won't index."""
    if not source.strip():
        return []
    package = _package_of(source)
    class_name = _primary_class(source)
    chunks: list[Chunk] = []

    header = _class_header_text(source, CLASS_HEADER_MAX_CHARS)
    if header.strip():
        chunks.append(
            Chunk(
                file=rel_path,
                package=package,
                class_name=class_name,
                method_name=None,
                kind="class_header",
                start_line=1,
                end_line=_line_of(source, len(header)),
                content=header,
            )
        )

    masked = _strip_comments_for_balance(source)
    seen_keys: set[tuple[int, str]] = set()  # (start_idx, name)
    for m in _METHOD_RE.finditer(masked):
        name = m.group("name")
        if name in _METHOD_BLACKLIST or name == class_name:
            continue
        # Locate the actual ``{`` (the regex consumes it as the last char).
        open_idx = m.end() - 1
        if open_idx >= len(masked) or masked[open_idx] != "{":
            continue
        key = (m.start(), name)
        if key in seen_keys:
            continue
        seen_keys.add(key)
        close_idx = _matching_brace(masked, open_idx)
        if close_idx <= open_idx:
            continue

        sig_start = m.start()
        # Snap signature start back to the start of its line for nicer previews.
        sig_start = source.rfind("\n", 0, sig_start) + 1

        body = source[sig_start: close_idx + 1]
        if len(body) > MAX_METHOD_CHARS:
            body = body[:MAX_METHOD_CHARS] + "\n// … (truncated)"

        if len(body) <= METHOD_TARGET_CHARS:
            chunks.append(
                Chunk(
                    file=rel_path,
                    package=package,
                    class_name=class_name,
                    method_name=name,
                    kind="method",
                    start_line=_line_of(source, sig_start),
                    end_line=_line_of(source, close_idx),
                    content=body,
                )
            )
        else:
            base_line = _line_of(source, sig_start)
            for rel_s, rel_e, slc in _window(
                body, METHOD_TARGET_CHARS, METHOD_OVERLAP_CHARS
            ):
                start_line = base_line + body.count("\n", 0, rel_s)
                end_line = base_line + body.count("\n", 0, rel_e)
                chunks.append(
                    Chunk(
                        file=rel_path,
                        package=package,
                        class_name=class_name,
                        method_name=name,
                        kind="method",
                        start_line=start_line,
                        end_line=end_line,
                        content=slc,
                    )
                )
    return chunks


@dataclass
class ChunkingStats:
    files_scanned: int = 0
    files_skipped: int = 0
    chunk_count: int = 0
    bytes_indexed: int = 0
    skipped_too_large: list[str] = field(default_factory=list)


def chunk_sources(
    sources_root: Path,
    *,
    suffixes: Iterable[str] = (".java", ".kt"),
) -> tuple[list[Chunk], ChunkingStats]:
    """Walk ``sources_root`` and chunk every supported source file.

    Returns ``(chunks, stats)``. The walker is deterministic (sorted) so
    rebuilds produce stable chunk ids.
    """
    stats = ChunkingStats()
    out: list[Chunk] = []
    suffix_set = set(suffixes)
    for p in sorted(sources_root.rglob("*")):
        if not p.is_file() or p.suffix not in suffix_set:
            continue
        rel = str(p.relative_to(sources_root))
        text = _read_file(p)
        if text is None:
            stats.files_skipped += 1
            stats.skipped_too_large.append(rel)
            continue
        stats.files_scanned += 1
        stats.bytes_indexed += len(text)
        for c in chunk_file(rel, text):
            out.append(c)
    stats.chunk_count = len(out)
    return out, stats
